a= int(input("Enter first number: "))
b= int(input("Enter second number: "))
print("The sum is: ",a+b)
print("The diference is: ",a-b)
print("The product is: ",a*b)
print("The division is: ",a/b)
print("The remainder is: ",a%b)
print("The floor division is: ",a//b)
print("The power is: ",a**b)